# Generated by Django 3.2.9 on 2021-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_createlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='bid',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
