# Generated by Django 3.2.9 on 2021-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_createlisting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='url',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
