# Generated by Django 3.2.9 on 2021-12-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listo',
            field=models.ForeignKey(default='2021', on_delete=django.db.models.deletion.CASCADE, related_name='commentar', to='auctions.createlisting'),
            preserve_default=False,
        ),
    ]
