# Generated by Django 3.2.9 on 2021-12-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_listo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listo',
        ),
        migrations.AddField(
            model_name='comment',
            name='listToComment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.createlisting'),
            preserve_default=False,
        ),
    ]
