# Generated by Django 3.2.9 on 2021-12-13 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211213_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userToComment',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
