# Generated by Django 3.2.9 on 2021-12-13 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='tags',
        ),
        migrations.AddField(
            model_name='createlisting',
            name='tags',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.tag'),
            preserve_default=False,
        ),
    ]
