# Generated by Django 3.2.9 on 2021-12-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_createlisting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userToComment',
            new_name='user',
        ),
    ]
