# Generated by Django 3.2.9 on 2021-12-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='bidding',
        ),
    ]
