# Generated by Django 3.2.9 on 2021-12-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_bid_listtobid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createlisting',
            old_name='bid',
            new_name='startingBid',
        ),
    ]
