# Generated by Django 3.2.9 on 2021-12-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_rename_bid_createlisting_startingbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidding',
            new_name='bid',
        ),
    ]
