# Generated by Django 3.2.9 on 2021-12-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20211219_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='bid',
        ),
    ]
