# Generated by Django 3.2.9 on 2021-12-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_bid_listtobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='currentbidder',
            field=models.CharField(default='timezone', max_length=20),
            preserve_default=False,
        ),
    ]
