# Generated by Django 3.2.9 on 2021-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_createlisting_currentbidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='currentbidder',
            field=models.TextField(max_length=20),
        ),
    ]
