# Generated by Django 3.2.9 on 2021-12-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_alter_createlisting_currentbidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='currentbidder',
        ),
    ]
