# Generated by Django 3.2.9 on 2021-12-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_remove_createlisting_currentbidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='currentbidder',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
