# Generated by Django 3.2.9 on 2021-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_createlisting_currentbidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='closing',
            field=models.BooleanField(default='False'),
        ),
    ]
