# Generated by Django 3.2.9 on 2021-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_alter_createlisting_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
