# Generated by Django 3.2.9 on 2021-12-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_alter_createlisting_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='picture',
        ),
    ]
